# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-27 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('pwd', models.CharField(max_length=50)),
                ('add_time', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ArtSingle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('add_time', models.IntegerField(default=0)),
                ('sort', models.IntegerField(default=0)),
                ('type', models.IntegerField(default=0)),
                ('hits', models.IntegerField(default=0)),
                ('picture', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DataClass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('parent_id', models.IntegerField(default=0)),
                ('sort', models.IntegerField(default=0)),
                ('type', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='dataclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simple.DataClass'),
        ),
    ]
