# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-23 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='用户姓名')),
                ('Pass', models.CharField(default='', max_length=255, verbose_name='用户密码')),
                ('sim', models.CharField(default='', max_length=255, verbose_name='用户手机')),
                ('icon', models.CharField(default='', max_length=255, verbose_name='用户图像')),
                ('idcard', models.CharField(default='', max_length=255, verbose_name='用户身份证')),
                ('money', models.CharField(default='', max_length=255, verbose_name='金钱')),
                ('same', models.CharField(default='', max_length=255, verbose_name='是否一致')),
                ('sex', models.CharField(default='', max_length=255, verbose_name='性别')),
                ('tel', models.CharField(default='', max_length=255, verbose_name='用户账户')),
                ('token', models.CharField(default='', max_length=255, verbose_name='秘钥')),
                ('login', models.CharField(default='', max_length=255, verbose_name='登录')),
                ('certificate', models.CharField(default='', max_length=255, verbose_name='副参')),
                ('section', models.CharField(default='', max_length=255, verbose_name='副参')),
                ('title', models.CharField(default='', max_length=255, verbose_name='说明')),
                ('createdate', models.CharField(default='', max_length=255, verbose_name='注册日期')),
            ],
        ),
    ]
