# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-27 07:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_info',
            options={'verbose_name': '用户分组', 'verbose_name_plural': '用户信息'},
        ),
    ]
